apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
  namespace: secure-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: secure-auth-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: secure-auth-config
            - secretRef:
                name: secure-auth-secrets
          volumeMounts:
            - name: auth-data
              mountPath: /app/data
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: auth-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: secure-auth
spec:
  type: ClusterIP
  selector:
    app: auth-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
